# Generated by Django 3.1.4 on 2020-12-23 03:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, null=True)),
                ('url', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('has_made', models.BooleanField(default=False)),
                ('img_src', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('rating', models.IntegerField(default=0)),
                ('tags', models.JSONField(default=[])),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
