# Generated by Django 3.1.4 on 2021-01-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210110_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeitem',
            name='notes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
