# Generated by Django 3.1.4 on 2023-02-14 20:55

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawledRecipeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, null=True)),
                ('url', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('has_made', models.BooleanField(default=False)),
                ('img_src', models.CharField(blank=True, max_length=900)),
                ('notes', models.JSONField(default=list)),
                ('rating', models.IntegerField(default=0)),
                ('tags', models.JSONField(default=list)),
                ('ingredients', models.TextField(blank=True)),
                ('steps', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ImageItem',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, null=True)),
                ('url', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('has_made', models.BooleanField(default=False)),
                ('img_src', models.CharField(blank=True, max_length=900)),
                ('notes', models.JSONField(default=list)),
                ('rating', models.IntegerField(default=0)),
                ('tags', models.JSONField(default=list)),
                ('ingredients', models.TextField(blank=True, default='')),
                ('steps', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
