# Generated by Django 3.1.4 on 2021-01-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeitem',
            name='notes',
            field=models.JSONField(default=[]),
        ),
    ]
