# Generated by Django 3.1.4 on 2023-02-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageitem',
            name='unique_id',
            field=models.CharField(default='<function uuid4 at 0x7fe3f025baf0>', editable=False, max_length=100, null=True, unique=True),
        ),
    ]
