# Generated by Django 3.1.4 on 2021-02-04 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210201_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawledrecipeitem',
            name='img_src',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='crawledrecipeitem',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='crawledrecipeitem',
            name='url',
            field=models.CharField(max_length=300),
        ),
    ]
