# Generated by Django 3.1.4 on 2021-05-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210204_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawledrecipeitem',
            name='img_src',
            field=models.CharField(blank=True, max_length=900),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='img_src',
            field=models.CharField(blank=True, max_length=900),
        ),
    ]
