# Generated by Django 3.1.4 on 2023-02-12 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20230212_0312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageitem',
            name='title',
        ),
    ]
