# Generated by Django 3.1.4 on 2023-02-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20230212_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
