# Generated by Django 3.1.4 on 2023-02-14 03:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20230212_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageitem',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
