# Generated by Django 3.1.4 on 2021-01-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210110_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeitem',
            name='notes',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='tags',
            field=models.JSONField(default=[]),
        ),
    ]
