# Generated by Django 3.1.4 on 2021-01-14 02:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210110_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawledRecipeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, null=True)),
                ('url', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('has_made', models.BooleanField(default=False)),
                ('img_src', models.CharField(blank=True, max_length=200)),
                ('notes', models.JSONField(default=list)),
                ('rating', models.IntegerField(default=0)),
                ('tags', models.JSONField(default=list)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
