# Generated by Django 3.1.4 on 2023-02-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20230212_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageitem',
            name='unique_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
