# Generated by Django 3.1.4 on 2023-02-12 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20230212_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageitem',
            old_name='id',
            new_name='unique_id',
        ),
    ]
