# Generated by Django 3.1.4 on 2023-02-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_imageitem_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageitem',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='unique_id',
            field=models.CharField(editable=False, max_length=100, null=True, unique=True),
        ),
    ]
