# Generated by Django 3.1.4 on 2023-02-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20230214_1936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageItem',
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='ingredients',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='steps',
            field=models.TextField(blank=True, default=''),
        ),
    ]
